---
title: "Character Model Training Report"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyr)
library(ggplot2)
library(knitr)
characterDataPath <- './results/wordLstm6.csv'

```

## Training data

```{r, echo=FALSE}
loadCharacterData <- function() {
  data <- as.data.frame(read.csv(characterDataPath, header=FALSE, col.names=c('epoch', 'accuracy', 'loss', 'rate', 'minibatch')))
  data$index <- as.numeric(rownames(data))
  data
}

characterData <- loadCharacterData()

top10 <- characterData %>%
  select(index, accuracy, loss) %>%
  arrange(desc(accuracy), desc(loss)) %>%
  head(10)

top10 %>%
  kable()
```

```{r, echo=FALSE}
topIndex <- max(characterData$index)
disappointment <- sum(topIndex:(topIndex - 9)/top10$index)/10 -1

characterData %>%
  summarize(maxAcc = max(accuracy),minAcc=min(accuracy), maxLoss = max(loss), minLoss=min(loss), epochs=max(index), disappointment=disappointment) %>%
  kable()
```




## Training plots

```{r echo=FALSE, fig.width=12, fig.height = 8}
meanAcc <- mean(characterData$accuracy)
meanLoss <- mean(characterData$loss)
maxIndex <- max(characterData$index)
multiplier <- 1e2
meanGlobal <- meanAcc - multiplier*meanLoss

characterData %>%
  select(index, accuracy, loss) %>%
  filter(index > maxIndex - 1000) %>%
  mutate(global = accuracy - multiplier*loss) %>%
  gather('metric', 'value', -index) %>%
  ggplot(aes(x=index, y=value, color=metric)) +
    geom_smooth(method='loess', span=0.25) +
    geom_line(alpha=0.3) +
    geom_line(aes(y=meanAcc), color='red', linetype='dashed') +
    geom_line(aes(y=meanLoss), color='blue', linetype='dashed') +
    geom_line(aes(y=meanGlobal), color='green', linetype='dashed') +
    geom_text(aes(x=min(index), y=meanAcc + 0.01, label=round(meanAcc, 3)), angle=0, hjust="left", size=4.2, fontface="plain", color="grey") +
    geom_text(aes(x=min(index), y=meanLoss + 0.01, label=round(meanLoss, 3)), angle=0, hjust="left", size=4.2, fontface="plain", color="grey") +
    geom_text(aes(x=min(index), y=meanGlobal + 0.02, label=round(meanGlobal, 3)), angle=0, hjust="left", size=4.2, fontface="plain", color="grey")
```


```{r echo = FALSE}
characterData %>%
  select(index, accuracy, loss) %>%
  filter(index > maxIndex - 1000) %>%
  ggplot(aes(x=index, y=accuracy)) +
    geom_smooth(method='loess', span=0.5) +
    geom_line(alpha=0.3)
```

```{r echo = FALSE}
characterData %>%
  select(index, accuracy, loss) %>%
  filter(index > maxIndex - 1000) %>%
  ggplot(aes(x=index, y=loss)) +
    geom_smooth(method='loess', span=0.5) +
    geom_line(alpha=0.3)
```